using System.Reflection;
using FoodSafe.Permissions;
using FoodSafe.Security;
using Xunit;

namespace FoodSafe.Security;

public sealed class CurrentUserContextPermissionContractTests
{
    [Fact]
    public void Frontend_permission_projection_includes_business_management()
    {
        var field = typeof(CurrentUserContextAppService).GetField(
            "FoodSafePermissionNames",
            BindingFlags.NonPublic | BindingFlags.Static);

        var permissions = Assert.IsType<string[]>(field?.GetValue(null));

        Assert.Contains(
            FoodSafePermissions.BusinessManagement.Businesses.View,
            permissions);
        Assert.Contains(
            FoodSafePermissions.BusinessManagement.Businesses.Create,
            permissions);
        Assert.Contains(
            FoodSafePermissions.BusinessManagement.Businesses.Edit,
            permissions);
        Assert.Contains(
            FoodSafePermissions.BusinessManagement.Businesses.Delete,
            permissions);
        Assert.Contains(
            FoodSafePermissions.BusinessManagement.Businesses.Import,
            permissions);
        Assert.Contains(
            FoodSafePermissions.BusinessManagement.Products.View,
            permissions);
        Assert.Contains(
            FoodSafePermissions.BusinessManagement.Products.Create,
            permissions);
        Assert.Contains(
            FoodSafePermissions.BusinessManagement.Products.Edit,
            permissions);
        Assert.Contains(
            FoodSafePermissions.BusinessManagement.Products.Delete,
            permissions);
        Assert.Contains(
            FoodSafePermissions.BusinessManagement.SelfDeclarations.View,
            permissions);
        Assert.Contains(
            FoodSafePermissions.BusinessManagement.SelfDeclarations.Create,
            permissions);
        Assert.Contains(
            FoodSafePermissions.BusinessManagement.SelfDeclarations.Edit,
            permissions);
        Assert.Contains(
            FoodSafePermissions.BusinessManagement.SelfDeclarations.Delete,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.ProductRegistrations.View,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.ProductRegistrations.Create,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.ProductRegistrations.Edit,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.ProductRegistrations.Delete,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.AdRegistrations.View,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.AdRegistrations.Create,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.AdRegistrations.Edit,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.AdRegistrations.Delete,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.EligibilityCertificates.View,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.EligibilityCertificates.Create,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.EligibilityCertificates.Edit,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.EligibilityCertificates.Delete,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.CfsCertificates.View,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.CfsCertificates.Create,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.CfsCertificates.Edit,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.CfsCertificates.Delete,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.ExportCertificates.View,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.ExportCertificates.Create,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.ExportCertificates.Edit,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Licensing.ExportCertificates.Delete,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Inspection.Plans.View,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Inspection.Plans.Create,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Inspection.Plans.Edit,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Inspection.Plans.Delete,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Inspection.Plans.Approve,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Inspection.Results.View,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Inspection.Results.Create,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Inspection.Results.Edit,
            permissions);
        Assert.Contains(
            FoodSafePermissions.Inspection.Results.Delete,
            permissions);
        Assert.Contains(
            FoodSafePermissions.AlertsAndTesting.Alerts.View,
            permissions);
        Assert.Contains(
            FoodSafePermissions.AlertsAndTesting.Alerts.Create,
            permissions);
        Assert.Contains(
            FoodSafePermissions.AlertsAndTesting.Alerts.Edit,
            permissions);
        Assert.Contains(
            FoodSafePermissions.AlertsAndTesting.Alerts.Delete,
            permissions);
        Assert.Contains(
            FoodSafePermissions.AlertsAndTesting.Alerts.Publish,
            permissions);
        Assert.Contains(
            FoodSafePermissions.AlertsAndTesting.News.View,
            permissions);
        Assert.Contains(
            FoodSafePermissions.AlertsAndTesting.News.Create,
            permissions);
        Assert.Contains(
            FoodSafePermissions.AlertsAndTesting.News.Edit,
            permissions);
        Assert.Contains(
            FoodSafePermissions.AlertsAndTesting.News.Delete,
            permissions);
        Assert.Contains(
            FoodSafePermissions.AlertsAndTesting.News.Publish,
            permissions);
    }
}
